services:
  - type: web
    name: app-service
    env: docker
    dockerfilePath: ./Dockerfile-app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001 # The port app.py runs on
    routes:
      - pathPrefix: /app

  - type: web
    name: gui-service
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000 # The port gui.py runs on
    routes:
      - pathPrefix: /gui
