services:
  - type: web
    name: app-service
    env: docker
    dockerfilePath: ./Dockerfile-app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001 # The port app.py runs on
    routes:
      - name: app-service-route
        path: /app/*
        service: app-service

  - type: web
    name: gui-service
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000 # The port gui.py runs on
    routes:
      - name: gui-service-route
        path: /gui/*
        service: gui-service
