services:
  - type: web
    name: app-service
    env: docker
    dockerfilePath: ./Dockerfile-app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001

  - type: web
    name: gui-service
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
